import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GoogleAnalytics } from "@next/third-parties/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import { FilterProvider } from "@/context/FilterContext";
import { JobsDataProvider } from "@/context/JobsDataContext";
//import GoogleTranslate from "@/components/GoogleTranslate/GoogleTranslate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FilterProvider>
          <JobsDataProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <div className="min-h-screen flex flex-col">
                <Header />
                <div className="flex-1">{children}</div>
                <Footer />
              </div>
              {process.env.NEXT_PUBLIC_IS_PRODUCTION && (
                <GoogleAnalytics gaId="G-4QYJWXXMRR" />
              )}
            </ThemeProvider>
          </JobsDataProvider>
        </FilterProvider>
      </body>
    </html>
  );
}
